#以下学习元组（与列表相似，但元素不能修改），所以基本上不会使用空元组，它也可以保护数据安全
tuple1=(23,"小明",12.3,12.3)
print(type(tuple1))#明确变量的类型
print(tuple1[2])#用中括号进行索引
tuple2=(5,)#定义一个元素的元组，需加一个逗号来明确元素的类型，不能像int（）来改变变量类型,但在元组与列表可以相互修改
print(type(tuple2))
#以下学习元组的操作(count,index)
print(tuple1.index(23))#取索引是明确一个元素在元组中的位置
print(tuple1.count(12.3))#这个是明确一个元素在元组中出现的次数
print(len(tuple1))#明确元组中元素
#以下学习元组的循环遍历（for）
for my_infor in tuple1:
    print(my_infor)
#每一个元素执行一个相同的代码
#格式化字符串后面多个变量而使用的括号就是元组
name=("霞姐","小姐","小明")
print("这个班的学生名字有:%s,%s,%s"%name)#格式化字符串要一一对应
#以下学习元组与列表之间的转换，就像数据类型之间的修改（int()）
name1=["张三","王五"]
name2=tuple(name1)
print(type(name2))
#list同理
#以下学习字典,可以用来描述一个事物，比较灵活，它与列表最大的区别是是否有序
小明={"name":"小明",
    "age":18,
    "height":1.73}#把每一个键值对看成一个整体
print(小明["age"])#取值
#key一定要加",因为它是str，不然会被认为是一个变量
小明["hansun"]="ture"#增加一个key与相对应的数据
小明["name"]="小小明"#如果存在，则变为了修改
小明.pop("age")#做一个删除
print(小明)
print(len(小明))#统计键值对的数量
#以下来学合并，在新键一个键值对（update）
张三={"name":"张三",
    "age":19,
    "height":1.76}
小明.update(张三)#已经存在的键值对则会被直接覆盖
print(小明)
小明.clear()
print(小明)#全部清空
#以下来学习循环遍历,因为数据类型基本上不相同，所以一般都不会使用循环遍历
for k in 张三:
    print("%s——%s"%(k,张三[k]))
#字典就是无序的，我的python版本还高，在3.7以后的版本默认输出字典按顺序，但它的数据就是无序的
#可以把一个字典的整体放到列表里，充当一个元素
card_list=[
    {"name":"xiaojie",#列表是由序的，字典是无序的
     "qq":123456},
    {"name":"zhangsan",
     "qq":123457},
]
print(card_list)
#以下学习字符串
str1='我的外号是"小杰"'#大部分的时候都是用是用双引号，如果想在文字里加双引号,则最外面使用单引号
print(str1)
print(str1[5])#双引号也会被标一个序号，同理空格也算
str2="hallo"
for char in str2:
    print(char)#字符串的循环遍历
print(len(str2))
print(str2.count("ll"))#统计子字符串个数，如果没有则会显示0
print(str2.index("a"))#还是用index进行索引

